### ISSUE TITLE
"Repostitory structure for master is not compliant" Error

### ISSUE THREAD

**Issue by rainmakertwo3** [snowzach/hassio-addons#11]
Hello,
 
I'm getting the above error message when I tried to install this software. Here are my steps:
- At Hacs tab, selected the "Custom repositories".
- Added the following "https://github.com/snowzach/hassio-addons.git" URL and selected "Integration" at Category. 
- The respond was the above message.

FYI, here are my setup:
- Core, core-2021.2.2
- supervisor-2021.02.6
- Home Assistant OS 5.11
- Hacs, Integration version: | 1.11.2

Is there an available documentation that  could help me to resolve this issue? Thank you in advance.
-- | --

**Comment by snowzach** [comment]
@frenck any idea if this is related to the PR you made? I will try to boot up HassIO tomorrow.

**Comment by frenck** [comment]
HACS....

**Comment by snowzach** [comment]
@rainmakertwo3 I don't know what HACS is, but I booted up Hass.IO and added my repo and it worked fine. I'm not sure I can help you with that one.

**Comment by rainmakertwo3** [comment]
> @rainmakertwo3 I don't know what HACS is, but I booted up Hass.IO and added my repo and it worked fine. I'm not sure I can help you with that one.

I'm trying to install the software via HACS Store GUI on my rasp. I'm not sure if the photo attached below would be any help. In any case, it's ok if you can't replicate my error. I just thought maybe you have seen this installation error and have a ready solution. Thank you again for replying to my question. 
 
<img width="1161" alt="Screenshot 2021-02-11" src="https://user-images.githubusercontent.com/78856640/107608423-ea6ec200-6c76-11eb-9a2c-1727e394744e.png">

**Comment by frenck** [comment]
HACS is for installing custom integrations, this is an addon. Addons and integrations are NOT the same things. 

Indeed this will not work and has never worked. Please use the addon store in the supervisor panel.


@snowzach i am opening a pr to revert my change. It works, but I am not going to maintain your addon or be your helpdesk a mention away.

**Comment by snowzach** [comment]
@frenck I appreciate your PR and chiming in here and as you can see, I tried it out and it worked fine. If you don't have time, don't reply. No big deal.
