### ISSUE TITLE
Unable to start the add-on 

### ISSUE THREAD

**Issue by backslashV** [snowzach/hassio-addons#21]
Hi,
I get this error in the logs when I try to start the addon:

[FATAL tini (7)] exec /opt/doods/doods failed: Exec format error

Version installed on Raspberry Pi 4 running Home Assistant OS v2022.2.9:
DOODS-amd64
Current version: 2 (Changelog)

Any help is appreciated.

**Comment by snowzach** [comment]
You need to pick the DOODS-arm64 addon.. amd64 won't work on a pi
