### ISSUE TITLE
DOODS does not start on boot

### ISSUE THREAD

**Issue by rostikk80** [snowzach/hassio-addons#3]
After rebooting Hassio Doods needs to be started manually. Here is the log:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x5eaa00]
goroutine 1 [running]:
github.com/snowzach/doods/detector/tflite.(*InterpreterOptions).AddDelegate.func1(0x3410968, 0x0, 0x0)
	/build/detector/tflite/tflite.go:82 +0x14
github.com/snowzach/doods/detector/tflite.(*InterpreterOptions).AddDelegate(0x3410968, 0x0, 0x0)
	/build/detector/tflite/tflite.go:82 +0x2c
github.com/snowzach/doods/detector/tflite.New(0x356c660, 0x0, 0x0, 0x0)
	/build/detector/tflite/detector.go:102 +0x77c
github.com/snowzach/doods/detector.New(0x2)
	/build/detector/detector.go:62 +0x67c
github.com/snowzach/doods/cmd.glob..func1(0xca7f20, 0x3570100, 0x0, 0x2)
	/build/cmd/api.go:25 +0x14
github.com/spf13/cobra.(*Command).execute(0xca7f20, 0x35700f0, 0x2, 0x2, 0xca7f20, 0x35700f0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x1f4
github.com/spf13/cobra.(*Command).ExecuteC(0xca8060, 0x1, 0x1a52c, 0x345e070)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x230
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/snowzach/doods/cmd.Execute()
	/build/cmd/root.go:57 +0x20
main.main()
	/build/main.go:8 +0x14

**Comment by snowzach** [comment]
Can you include your config?

**Comment by rostikk80** [comment]
Here is the config:
{
  "server": {
    "port": "8080"
  },
  "auth_key": "",
  "doods.detectors": [
    {
      "name": "edgetpuCOCO",
      "type": "tflite",
      "modelFile": "/share/doods/models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite",
      "labelFile": "/share/doods/models/coco_labels.txt",
      "numThreads": 1,
      "numConcurrent": 1,
      "hwAccel": true
    }
  ]
}

**Comment by snowzach** [comment]
Have a try again.
