### ISSUE TITLE
Port change to 8181

### ISSUE THREAD

**Issue by rain82k** [snowzach/hassio-addons#6]
Hi there,

Unfortunately, I'm completely new to the Home Assistant. I now wanted to install doods via Hass.io and cannot use this because port 8080 is already being used by facebox. Can I move the port to 8181?
Unfortunately I don't know what the name of the config file should be and whether it should be in "/ home-assistant / share"?

**Comment by snowzach** [comment]
You should be able to set the config in there with 
```
{
  "server": {
    "port": "8080"
  },
......
```

**Comment by kcdc80** [comment]
I actually have the same issue, tried to change to another port, but doods add-on does not start.
